spring:
  profiles:
    active: root
  datasource:
    url: jdbc:mysql://localhost:3306/mirsal
    username: root
    password: Eyadsql2816.
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8081
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
